
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author LENOVO
 */
public class DeleteStudentDetails extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeleteStudentDetails
     */
    public DeleteStudentDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        jLabel1.setText("DELETE STUDENT DETAILS");

        jLabel2.setText("ROLL");

        jLabel3.setText("NAME");

        jLabel4.setText("CLASS");

        jLabel5.setText("SECTION");

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("CANCEL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(295, 295, 295))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)
                                .addGap(97, 97, 97)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1)
                            .addComponent(jTextField2)
                            .addComponent(jTextField3)
                            .addComponent(jTextField4)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(0, 13, Short.MAX_VALUE)))))
                .addGap(127, 127, 127))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                // TODO add your handling code here:
          String USERNAME="root";
        String PASSWORD="";
        String CONN_STRING="jdbc:mysql://localhost:3308/user";
        Connection conn=null;
        
        try
        {
          
          //System.out.print("connected");
          //conn= DriverManager.getConnection( CONN_STRING,USERNAME,PASSWORD);
          
          conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
          
          System.out.print("Connected");
               
                String st1=jTextField1.getText().trim();  //roll
                String query="select roll,name,class,section from NewAdmission where roll='"+st1+"'";
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                ResultSet rs=preparedStmt.executeQuery(query);
                //boolean v=preparedStmt.execute(); 
                //System.out.print("\nvalue :"+v);
                
         
          
            String st2="",st3="",st4="";           
               
                boolean found=false;
                 while(rs.next()){
                 
                 
                 st1=rs.getString("roll");  
                 st2=rs.getString("name");  
                 st3=rs.getString("class");
                 st4=rs.getString("section");
                
                 found=true;
                 }
                 
                 if(found==true)
                 {
                 jTextField1.setText(st1);
                 jTextField2.setText(st2);
                 jTextField3.setText(st3);
                 jTextField4.setText(st4);
                 
                 }
                 else
                 {
                     JFrame f=new JFrame();        
                     JOptionPane.showMessageDialog(f,"Roll "+st1+" does not exist ","ANIK",JOptionPane.WARNING_MESSAGE);  
                 }   
                 conn.close();
             } 
                
        catch(SQLException e)
        {            
            JFrame f=new JFrame();
            //System.out.print(e.getMessage());
            JOptionPane.showMessageDialog(f,"Some Fields are empty or User ID already exist "+e.getMessage(),"ANIK",JOptionPane.WARNING_MESSAGE); 
            //JOptionPane.showMessageDialog(f,"Some Fields are empty or User ID already exist "+e,"ANIK",JOptionPane.WARNING_MESSAGE); 
        }  
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        
        
          String USERNAME="root";
        String PASSWORD="";
        String CONN_STRING="jdbc:mysql://localhost:3308/user";
        Connection conn=null;
        
        try
        {
          
          //System.out.print("connected");
          //conn= DriverManager.getConnection( CONN_STRING,USERNAME,PASSWORD);
          
          conn=DriverManager.getConnection(CONN_STRING,USERNAME,PASSWORD);
          //Statement stmt=conn.createStatement();
          
         // Statement stmt=(Statement) conn.createStatement();
          
            String st1="",st2="",st3="",st4="";           
          st1=jTextField1.getText().trim(); //ROLL
          st2=jTextField2.getText().trim();  //NAME
          st3=jTextField3.getText().trim();  //class
          st4=jTextField4.getText().trim();  //section
                String query = " delete from NewAdmission where roll='"+st1+"'";
                PreparedStatement preparedStmt = conn.prepareStatement(query);
                preparedStmt.setString (1, st1);
                preparedStmt.setString (2,  st2);  
                preparedStmt.setString (3,  st3);    
                preparedStmt.setString (4,  st4);    
                boolean v=preparedStmt.execute();    
                JFrame f=new JFrame();
                JOptionPane.showMessageDialog(f,st1+" "+st2+" "+st3+" "+st4+" Your Profile has been created sucessfully","Anik ",JOptionPane.WARNING_MESSAGE);  
                
                this.dispose(); 
          
             } 
        
        
        catch(SQLException e)
        {            
            JFrame f=new JFrame();
            JOptionPane.showMessageDialog(f,"Some Fields are empty or User ID already exist "+e,"ANIK",JOptionPane.WARNING_MESSAGE); 
        }  
        
        

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
